repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.0.3
  hooks:
    - id: sqlfluff-lint
      # For dbt projects, this installs the dbt "extras".
      # You will need to select the relevant dbt adapter for your dialect
      # (https://docs.getdbt.com/docs/available-adapters):
      additional_dependencies: ['dbt-snowflake==1.3', 'sqlfluff-templater-dbt']
      args: [--dialect, "snowflake"]
    # - id: sqlfluff-fix
      # Arbitrary arguments to show an example
      # args: [--rules, "L003,L014"]
      # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']