name: refresh docs

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:
    
permissions:
  id-token: write
env:
  AWS_REGION : "eu-west-1" #Change to reflect your Region
    
jobs:

  generate_docs:
    name: run docs
    runs-on: ubuntu-latest

  # Set the environment variables needed for the run
    env:
      dvd_sf_db: ${{  secrets.DVD_SF_DB }} 
      dvd_sf_schema: ${{  secrets.DVD_SF_SCHEMA }} 
      dvd_sf_wh: ${{  secrets.DVD_FROSTY_WH }} 
      dvd_sf_user: ${{ secrets.DVD_SF_USER }}
      dvd_sf_role: ${{ secrets.DVD_SF_ROLE }}
      dvd_sf_account: ${{ secrets.DVD_SF_ACCOUNT }}
      dvd_sf_passphrase: ${{ secrets.DVD_SF_PASSPHRASE }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      AWS_EXPORT: ${{ secrets.AWS_EXPORT }}
      # easier to have the combined aws_export (that exports the 
      # three AWS_secrets needed)
      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
      AWS_EC2_METADATA_DISABLED: true

    steps:
      - uses: "actions/checkout@v3"

      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::344768802373:role/dvd_github_frostyfridays_bucket_access
          #change to reflect your IAM role’s ARN
          role-session-name: dvd_frosty_friday
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true
      - name: Sts GetCallerIdentity
        id: sts
        run: |
          aws sts get-caller-identity

      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: pk
        run: |
          pwd 
          echo "-----BEGIN ENCRYPTED PRIVATE KEY-----" >> ./rsa_key_david_sf.p8
          echo ${{ secrets.SSH_KEY }} >> ./rsa_key_david_sf.p8 
          echo "-----END ENCRYPTED PRIVATE KEY-----" >> ./rsa_key_david_sf.p8
          echo $AWS_EXPORT >> ./aws_export
          source ./aws_export 

      - name: install requirements
        run: "pip install -r requirements.txt"
      - name: install aws
        run: |
          echo "Starting apt-spy"
          sudo gem install apt-spy2
          sudo apt-spy2 check
          sudo apt-spy2 fix --commit
          sudo sed -i 's/utah\.//' /etc/apt/sources.list
          echo "Starting apt-get update"
          sudo apt-get update
          sudo sed -i 's/utah\.//' /etc/apt/sources.list
          echo "Starting apt-get install"
          sudo apt-get install -yqq awscli
      - name: dbt docs generate
        run: |
          pwd
          # source ./aws_export
          echo "key"
          cat ./rsa_key_david_sf.p8 
          chmod 644 ./rsa_key_david_sf.p8 
          export DBT_PROFILES_DIR=$(pwd)/profiles
          dbt debug --target cicd
          echo "installing deps"
          dbt deps
          echo "generating docs"
          dbt docs generate --target cicd
          echo "keeping only frosty"
          cp ./extra/change_manifest.py ./target
          cd target
          python change_manifest.py
          echo "uploading to s3"
          aws s3 cp ./output/manifest.json  s3://dvd-il-bucket-public/manifest.json
          aws s3 cp ./output/catalog.json  s3://dvd-il-bucket-public/catalog.json
          aws s3 cp ./index.html  s3://dvd-il-bucket-public/index.html
      - name: say gg
        run: |
          echo "we're done"
